### ISSUE TITLE
Estado personalizado para el usuario

### ISSUE THREAD

**Issue by manucabral** [TeamParches/parches-chat-backend#3]
Agregar un campo llamado "customStatus" al modelo del usuario. Tener en cuenta también modificar el UserType.

**Comment by larayavrs** [comment]
Se añadio el estado personalizado al usuario, tendrá un estado por defecto y puede ser modificado.

### Evidencias
![](https://i.imgur.com/zl3PzmX.png)

**Comment by manucabral** [comment]
Acordate que tienes que hacer pull request así se cierra el issue.
